movieproject/movieapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import  views
app_name = 'movieapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movieId>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.updatemovie,name ='updatemovie'),
    path('delete/<int:id>/',views.delete,name ='delete')

    # path('movie/<int:movieId>/', views.urlpage, name='urlpage')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name = models.CharField(max_length=120)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

def __str__(self):
    return self.name

movieproject/movieapp/forms.py
from django import  forms
from . models import movie
class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from . models import movie
from  . forms import  movieform

# Create your views here.

def index(request):
    movies=movie.objects.all()
    context={'movies_list':movies}
    return render(request,'index.html',context)
def detail(request,movieId):
    mmovie=movie.objects.get(id=movieId)
    return render(request,"detail.html",{'movielist':mmovie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        imge = request.FILES['image']
        movielist=movie(name=name,desc=desc,year=year,img=imge)
        movielist.save()
    return render(request,"add.html")
def updatemovie(request,id):
    movies=movie.objects.get(id=id)
    form=movieform(request.POST or None, request.FILES,instance=movies)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movies':movies})
def delete(request,id):
    if request.method=='POST':
        movies=movie.objects.get(id=id)
        movies.delete()
        return redirect('/')
    return render(request,'delete.html')



# def urlpage(request,movieId):
#     mmovie=movie.objects.get(id=movieId)
#     return render(request,"detail.html",{'movielist':mmovie})

movieproject/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3 style="background-color:red">hai welcome to add file</h3>
{% extends 'base.html' %}
{% block body  %}
<form METHOD="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter your movie nme?"><br>
     <input type="text" name="desc" placeholder="Enter your movie description?"><br>
     <input type="number" name="year" placeholder="Enter releasing year?"><br>
     <input type="file" name="image" ><br>
    <input type="submit">
</form>
{% endblock %}
</body>
</html>

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    online movie store
  </a>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this movie?
    <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body  %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movielist.img.url}}" width="300" height="300">
        </div>
<div class="col-md-6">
   <h2>{{movielist.name}}</h2>
    <h4>{{movielist.desc}}</h4>
    <h6>{{movielist.year}}</h6>
     <a class="btn btn-warning" href="{% url 'movieapp:updatemovie' movielist.id %}">UPDATE</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movielist.id %}">DELETE</a>
</div>



         </div>
</div>

{% endblock %}

<!--</body>-->
<!--</html>-->

movieproject/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block body  %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}
</body>
</html>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movies_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">CLICK ME</a>
  </div>
</div>
        </div>

{% endfor %}
    </div>
</div>
<h2>LIST OF OSCAR AWARD MOVIES</h2>
<!--{% for i in movies_list %}-->
<!--{{i.id}}&ndash;&gt;{{i.name}}-&#45;&#45;&ndash;&gt;{{i.desc}}&#45;&#45;&ndash;&gt;{{i.year}}<br>-->
<!--{% endfor %}-->
{% for i in movies_list %}
<!--<a href="movie/{{i.id}}">{{i.name}}<br>-->
<img src="{{i.img.url}}" width="100" height="100">
<a href="{% url 'movieapp:detail' i.id %}">{{i.name}}<br>
{% endfor %}
    {% endblock %}
</a>